name: fyp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_messaging: ^15.2.5
  geolocator: ^13.0.4
  sensors_plus: ^6.1.1
  flutter_blue_plus: ^1.35.5
  bluetooth_low_energy: ^6.0.2
  intl: ^0.20.2
  device_info_plus: ^11.3.0
  firebase_storage: ^12.4.5
  uuid: ^4.5.1
  tflite_flutter: ^0.11.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  location: ^8.0.0
  url_launcher: ^6.3.1


flutter:

  uses-material-design: true
  assets:
    - assets/model.tflite
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
